### ISSUE TITLE
List of Adopters

### ISSUE THREAD

**Issue by FabioPinheiro** [hyperledger/identus#1]
**Is your feature request related to a problem? Please describe.**
For newcomers would be nice to know what else is out there that is already using Identus.

**Describe the solution you'd like**
Would be nice to have a list of specific applications that adopted and using this technology/libraries.
Can be real applications are just demos.

**Additional context**
This question was mention on the end of the Identus `Community outreach call` meeting (2024/04/23)

**Comment by FabioPinheiro** [comment]
Demos like the ones in https://github.com/atala-community-projects
@elribonazo you also mention some identities wallets are ready using or at least developing with Identus. I think this repository would be a good place to put them.

**Comment by essbante-io** [comment]
We can do something about it. We need to come up with basic rules for things that can be listed so it doesn't become a billboard for advertising and a simple process to get submissions (Usually a PR) Some draft ideas: 
1) Must be Open Source
2) Must be available on GitHub (Or similar)
3) Must use Identus 
4) Build by active community members

**Comment by FabioPinheiro** [comment]
@essbante-io Other then the rule "Must use Identus" I disagree with the remaining 3 rules.

**Comment by essbante-io** [comment]
@FabioPinheiro Yeah, not even "Must use Identus" seems valid. Some community projects don't use Identus components but are extremely useful, or things like the Sandbox that are not open source but definitely belong to the List. I am concerned about establishing rules or clear entry criteria for listing projects because I have encountered instances where projects have misrepresented using this technology to benefit from community-based funding mechanisms. That kind of individual would love to get listed here as an "endorsement." Implementing governance measures will help prevent such issues and ensure that the project listed here is genuine. An endorsement from the Identus maintainers, like an invitation-only approach, could address this. What do you think? 

The project from @elribonazo and mixmix has enough endorsement,  and several other well-known projects from the community can be trusted and invited to be part of the list.

**Comment by FabioPinheiro** [comment]
This "endorsement" is should in no way be view as helper for community-based funding mechanisms.
It should follow a pattern, but we don't need a new processes or more rules for now.
This is an opinionated list. We can add and remove as we like. Anyone else can ask us to add and remove those "endorsement" references. It's going probably to be a while before we have any situation where the decision is not straightforward.

> The project from @elribonazo and mixmix has enough endorsement, and several other well-known projects from the community can be trusted and invited to be part of the list.
Those are good examples. Also we can go to the show and tell and review you all the meetings (the meeting notes). All the projects that were presented are probably good candidates.

**Comment by bsandmann** [comment]
I'd go with a rather open list in the beginning, and establish rules later if necessary. At the moment I think convincing people of trying out or even only considering Identus as part of their stack should be a high priority – and here every project we can showcase counts.

**Comment by essbante-io** [comment]
Thanks to everyone for your input. I'm working with Fay to get this going, and we'll have a showcase in the next few days.
